defaults:
  - models: siamese_config
  - dataloader: default_dataloader
  - _self_

trainer:
  dataset:
    train_size: 0.8

  optimizer:
    lr: 3.0e-4

  eval:
    top_n: 5
  
  params:
    accelerator: "gpu"  
    devices: 1  
    max_epochs: 50
    log_every_n_steps: 5
    enable_checkpointing: true  
    enable_progress_bar: true  
    deterministic: true  
    gradient_clip_val: 1.0  
    accumulate_grad_batches: 1 
    check_val_every_n_epoch: 5